export const GET_CHAR_LIST_SUCCESS = 'GET_CHAR_LIST_SUCCESS';
export const GET_CHAR_LIST_ERROR = 'GET_CHAR_LIST_ERROR';
export const GET_CHAR_LIST_PENDING = 'GET_CHAR_LIST_PENDING';
export const RESET_CHARLIST = 'RESET_CHARLIST';
export const GET_CHAR_DETAILS_SUCCESS = 'GET_CHAR_DETAILS_SUCCESS';
export const GET_CHAR_DETAILS_ERROR = 'GET_CHAR_DETAILS_ERROR';
export const GET_CHAR_DETAILS_PENDING = 'GET_CHAR_DETAILS_PENDING';
